#!/bin/bash

# Database Setup Instructions

echo "🔧 SaaS Application Setup"
echo "========================"
echo ""
echo "To fix the database connection error, you need to:"
echo ""
echo "1. Copy the environment template:"
echo "   cp .env.example .env"
echo ""
echo "2. Choose a database option:"
echo ""
echo "   Option A: Use a local SQLite database (easiest for development)"
echo "   - Update DATABASE_URL in .env to:"
echo "     DATABASE_URL=\"file:./dev.db\""
echo "   - Update prisma/schema.prisma provider to \"sqlite\""
echo ""
echo "   Option B: Use PostgreSQL locally"
echo "   - Install PostgreSQL"
echo "   - Create a database"
echo "   - Update DATABASE_URL in .env to your PostgreSQL connection string"
echo ""
echo "   Option C: Use a cloud database"
echo "   - Get a DATABASE_URL from services like:"
echo "     • Neon (https://neon.tech)"
echo "     • Supabase (https://supabase.com)"
echo "     • PlanetScale (https://planetscale.com)"
echo "     • Railway (https://railway.app)"
echo ""
echo "3. Set up other environment variables:"
echo "   - Get Cloudinary credentials from https://cloudinary.com"
echo "   - Get Clerk credentials from https://clerk.com"
echo ""
echo "4. Run database migrations:"
echo "   npx prisma migrate dev"
echo ""
echo "5. Generate Prisma client:"
echo "   npx prisma generate"
echo ""
echo "📝 For SQLite (quickest setup):"
echo "   1. cp .env.example .env"
echo "   2. Edit .env and set DATABASE_URL=\"file:./dev.db\""
echo "   3. Edit prisma/schema.prisma and change provider to \"sqlite\""
echo "   4. npx prisma migrate dev"
echo "   5. npm run dev"